
import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';

// 1. Load Environment Variables via dotenv
const __dirname = path.dirname(fileURLToPath(import.meta.url));
dotenv.config({ path: path.resolve(__dirname, '../../.env') });

const supabaseUrl = process.env.VITE_SUPABASE_URL;
const supabaseKey = process.env.VITE_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseKey) {
    console.error("Missing Supabase credentials in .env");
    process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

async function seed() {
    console.log("🌱 Starting Database Seed...");

    // ... (Existing cleanup/story logic remains conceptually same, but ensuring continued execution) ...
    // Note: To preserve existing context, I'm just replacing the top setup and the bottom user email
    // But replace_file_content replaces a block. I should replace header and footer separately?
    // or just use multi_replace. simpler to use replace for the whole file? No, file is large.
    // I will use multi_replace.

    // For this demo, let's assume we want a fresh start for THIS specific series
    console.log("Cleaning old demo data...");
    // We can't easily cascade delete without RLS policies allowing it, 
    // but the foreign keys should handle cleanup if we delete the parent series?
    // Let's just create new one for safety.

    // 1. Create Series
    console.log("Creating Series...");
    const { data: series, error: seriesError } = await supabase
        .from('series')
        .insert({
            title: 'Demos Técnicas ' + new Date().toISOString().slice(0, 10),
            description: 'Serie de pruebas para el motor Webtoon 2.0 generated by Request'
        })
        .select()
        .single();

    if (seriesError) throw new Error("Series creation failed: " + seriesError.message);
    const seriesId = series.id;
    console.log(`✅ Series created: ${seriesId}`);

    // 2. Create Chapter
    console.log("Creating Chapter...");
    const { data: chapter, error: chapterError } = await supabase
        .from('chapters')
        .insert({
            series_id: seriesId,
            title: 'El Misterio del Bosque Digital',
            order_index: 1,
            is_published: true
        })
        .select()
        .single();

    if (chapterError) throw new Error("Chapter creation failed: " + chapterError.message);
    const chapterId = chapter.id;
    console.log(`✅ Chapter created: ${chapterId}`);

    // 3. Create Nodes
    console.log("Creating Nodes...");

    // A. Start
    const { data: startNode, error: startError } = await supabase
        .from('story_nodes')
        .insert({ chapter_id: chapterId, image_url: '/assets/images/panel1.png', type: 'panel' })
        .select().single();
    if (startError) throw startError;

    // B. Stealth
    const { data: stealthNode, error: stealthError } = await supabase
        .from('story_nodes')
        .insert({ chapter_id: chapterId, image_url: '/assets/images/panel2.png', type: 'panel' })
        .select().single();
    if (stealthError) throw stealthError;

    // C. Shout
    const { data: shoutNode, error: shoutError } = await supabase
        .from('story_nodes')
        .insert({ chapter_id: chapterId, image_url: '/assets/images/panel3.png', type: 'panel' })
        .select().single();
    if (shoutError) throw shoutError;

    // D. End
    const { data: endNode, error: endError } = await supabase
        .from('story_nodes')
        .insert({ chapter_id: chapterId, image_url: '/assets/images/panel1.png', type: 'panel' }) // Placeholder
        .select().single();
    if (endError) throw endError;

    console.log("✅ Nodes created.");

    // 4. Create Dialogues
    console.log("Creating Dialogues...");
    const dialogues = [
        { node_id: startNode.id, speaker_name: 'Narrador', content: 'Te encuentras frente a la entrada del bosque prohibido. Una neblina digital cubre el camino.', position_y: 85 },
        { node_id: stealthNode.id, speaker_name: 'Narrador', content: 'Avanzas entre los árboles de código binario sin hacer ruido. Ves una luz azul a lo lejos.', position_y: 85 },
        { node_id: shoutNode.id, speaker_name: 'Sistema', content: '¡ALERTA! Tu grito despierta a los Glitches. Tienes que correr.', position_y: 85 },
        { node_id: endNode.id, speaker_name: '', content: 'Continuará...', position_y: 50 },
    ];
    const { error: dialError } = await supabase.from('dialogues').insert(dialogues);
    if (dialError) throw dialError;
    console.log("✅ Dialogues created.");

    // 5. Connect Choices
    console.log("Connecting Choices...");
    const choices = [
        { from_node_id: startNode.id, to_node_id: stealthNode.id, label: 'Entrar sigilosamente' },
        { from_node_id: startNode.id, to_node_id: shoutNode.id, label: 'Gritar "¡Hola Mundo!"' },
        { from_node_id: stealthNode.id, to_node_id: endNode.id, label: 'Siguiente' },
        { from_node_id: shoutNode.id, to_node_id: endNode.id, label: 'Huir' }
    ];
    const { error: choiceError } = await supabase.from('story_choices').insert(choices);
    if (choiceError) throw choiceError;
    console.log("✅ Choices connected for Demo.");

    // =========================================================================
    // NEW CONTENT: D&D, Batman, Rick & Morty
    // =========================================================================

    // --- Helper for creating a full story ---
    const createStory = async (title, desc, genre, coverUrl, nodesData) => {
        console.log(`\nCreating Series: ${title}...`);
        // 1. Series
        const { data: s } = await supabase.from('series').insert({ title, description: desc, genre, cover_url: coverUrl }).select().single();
        // 2. Chapter
        const { data: c } = await supabase.from('chapters').insert({ series_id: s.id, title: 'Capítulo 1', order_index: 1 }).select().single();

        const idMap = {}; // localIdx -> dbUuid

        // 3. Nodes (Sequential insert to keep IDs map simple)
        for (let i = 0; i < nodesData.length; i++) {
            const n = nodesData[i];
            const { data: node } = await supabase.from('story_nodes').insert({
                chapter_id: c.id,
                image_url: n.image || '/assets/images/panel1.png', // Fallback
                type: n.type || 'panel'
            }).select().single();
            if (!node) {
                console.error(`Failed to create node ${i} for ${title}`);
                continue;
            }
            idMap[i] = node.id;

            // Dialogues
            if (n.text) {
                await supabase.from('dialogues').insert({
                    node_id: node.id,
                    speaker_name: n.speaker || 'Narrador',
                    content: n.text,
                    position_y: 85
                });
            }
        }

        // 4. Connect Choices
        for (let i = 0; i < nodesData.length; i++) {
            const n = nodesData[i];
            if (n.choices) {
                for (const choice of n.choices) {
                    await supabase.from('story_choices').insert({
                        from_node_id: idMap[i],
                        to_node_id: idMap[choice.targetIndex],
                        label: choice.label
                    });
                }
            } else if (n.nextIndex !== undefined) {
                // Linear next
                // We don't have a 'next' field in DB, we represent it as a single choice usually or logic. 
                // But for this engine, a single choice works best for clarity.
                await supabase.from('story_choices').insert({
                    from_node_id: idMap[i],
                    to_node_id: idMap[n.nextIndex],
                    label: 'Continuar'
                });
            }
        }
        console.log(`✅ ${title} created.`);
    };

    // --- A. Dungeons & Dragons ---
    await createStory(
        'Dragones y Mazmorras: La Cripta',
        'Tu grupo ha caído en una emboscada.',
        'Fantasía',
        '/assets/images/cover_dnd.png',
        [
            /* 0 */ { text: "El goblin ríe mientras bloquea la salida. Tu espada pesa en tu mano.", speaker: "DM", choices: [{ label: "Atacar", targetIndex: 1 }, { label: "Dialogar", targetIndex: 2 }] },
            /* 1 */ { text: "¡Crítico! Cortas la cuerda del puente y el goblin cae al vacío.", speaker: "DM", nextIndex: 3 },
            /* 2 */ { text: "Intentas razonar, pero una flecha te roza la oreja. ¡Iniciativa!", speaker: "DM", nextIndex: 3 },
            /* 3 */ { text: "Del abismo surge un Beholder. Fin de la partida (por ahora).", speaker: "DM", type: 'ending' }
        ]
    );

    // --- B. Batman: Gotham Shadows ---
    await createStory(
        'Batman: Sombras de Gotham',
        'El Joker ha escondido una bomba. Tienes 5 minutos.',
        'Misterio',
        '/assets/images/cover_batman.png',
        [
            /* 0 */ { text: "La lluvia cae sobre la gárgola. La señal brilla en el cielo.", speaker: "Batman", choices: [{ label: "Ir al Muelle", targetIndex: 1 }, { label: "Ir al Banco", targetIndex: 2 }] },
            /* 1 */ { text: "Harley Quinn te espera con un mazo gigante.", speaker: "Alfred", nextIndex: 3 },
            /* 2 */ { text: "Es una trampa. Dos Caras ha bloqueado la bóveda.", speaker: "Oráculo", nextIndex: 3 },
            /* 3 */ { text: "Logras escapar usando el Bat-Gancho. La noche es joven.", speaker: "Narrador", type: 'ending' }
        ]
    );

    // --- C. Rick and Morty ---
    await createStory(
        'Rick y Morty: Aventura de 20 Minutos',
        'Entrar y salir, Morty. Rápido.',
        'Sci-Fi',
        '/assets/images/cover_rick.png',
        [
            /* 0 */ { text: "Morty, tienes que meterte estas semillas... ya sabes dónde.", speaker: "Rick", choices: [{ label: "¡Oh jeez, Rick!", targetIndex: 1 }, { label: "Ni hablar", targetIndex: 2 }] },
            /* 1 */ { text: "Bien hecho Morty. Ahora corre, la Federación Galáctica está aquí.", speaker: "Rick", nextIndex: 3 },
            /* 2 */ { text: "No seas aguafiestas Morty. Mira, ahora nos disparan.", speaker: "Rick", nextIndex: 3 },
            /* 3 */ { text: "Portal gun sin carga. Toca correr en círculos. Wubba Lubba Dub Dub!", speaker: "Rick", type: 'ending' }
        ]
    );

    // =========================================================================
    // USER REGISTRATION (Test User)
    // =========================================================================
    console.log("\n👤 Creating Test User...");
    const email = 'antigravity_test_user@gmail.com';
    const password = 'password123';

    // Attempt registration
    const { error: authError } = await supabase.auth.signUp({
        email,
        password,
    });

    if (authError) {
        console.log(`⚠️ User creation note: ${authError.message}`);
        // Likely 'User already registered', which is fine.
    } else {
        console.log(`✅ User Sign-up request sent for ${email}.`);
        console.log("   (If email confirmation is ON, you need to check the fake inbox or disable it in Supabase Dashboard)");
        console.log("   Credentials -> Email: test@test.com | Pass: password123");
    }

    console.log("\n🎉 SEEDING COMPLETE! 🎉");
}

seed().catch(err => {
    console.error("❌ Seed failed:", err);
    process.exit(1);
});
