-- PROFILES
create table if not exists public.profiles (
  id uuid references auth.users not null primary key
);

alter table public.profiles add column if not exists updated_at timestamp with time zone;
alter table public.profiles add column if not exists username text unique;
alter table public.profiles add column if not exists avatar_url text;
alter table public.profiles add column if not exists website text;

-- Row Level Security for Profiles
alter table public.profiles enable row level security;

-- Policies (Drop first to avoid duplication error on re-run)
drop policy if exists "Public profiles are viewable by everyone." on profiles;
create policy "Public profiles are viewable by everyone." on profiles for select using ( true );

drop policy if exists "Users can insert their own profile." on profiles;
create policy "Users can insert their own profile." on profiles for insert with check ( auth.uid() = id );

drop policy if exists "Users can update own profile." on profiles;
create policy "Users can update own profile." on profiles for update using ( auth.uid() = id );


-- TRANSACTIONS
create table if not exists public.transactions (
  id bigint generated by default as identity primary key
);

alter table public.transactions add column if not exists user_id uuid references auth.users not null;
alter table public.transactions add column if not exists amount decimal(12,2) not null default 0;
alter table public.transactions add column if not exists description text;
alter table public.transactions add column if not exists date timestamp with time zone default timezone('utc'::text, now()) not null;
alter table public.transactions add column if not exists type text check (type in ('income', 'expense')) not null default 'expense';
alter table public.transactions add column if not exists category text;
alter table public.transactions add column if not exists image_url text;
alter table public.transactions add column if not exists created_at timestamp with time zone default timezone('utc'::text, now()) not null;

-- Row Level Security for Transactions
alter table public.transactions enable row level security;

drop policy if exists "Users can view their own transactions." on transactions;
create policy "Users can view their own transactions." on transactions for select using ( auth.uid() = user_id );

drop policy if exists "Users can insert their own transactions." on transactions;
create policy "Users can insert their own transactions." on transactions for insert with check ( auth.uid() = user_id );

drop policy if exists "Users can update their own transactions." on transactions;
create policy "Users can update their own transactions." on transactions for update using ( auth.uid() = user_id );

drop policy if exists "Users can delete their own transactions." on transactions;
create policy "Users can delete their own transactions." on transactions for delete using ( auth.uid() = user_id );


-- STORAGE (Buckets)
insert into storage.buckets (id, name)
values ('receipts', 'receipts'), ('avatars', 'avatars')
on conflict (id) do nothing;

drop policy if exists "Receipts are publicly accessible." on storage.objects;
create policy "Receipts are publicly accessible." on storage.objects for select using ( bucket_id = 'receipts' or bucket_id = 'avatars' );

drop policy if exists "Users can upload their own receipts." on storage.objects;
create policy "Users can upload their own receipts." on storage.objects for insert with check ( (bucket_id = 'receipts' or bucket_id = 'avatars') and auth.uid() = owner );
