-- RECURRING TRANSACTIONS
create table if not exists public.recurring_transactions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  amount decimal(12,2) not null default 0,
  description text,
  type text check (type in ('income', 'expense')) not null default 'expense',
  category text,
  interval_unit text check (interval_unit in ('day', 'week', 'month', 'year')) not null,
  interval_value int not null default 1,
  start_date date not null,
  next_run_date date not null,
  active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Row Level Security
alter table public.recurring_transactions enable row level security;

drop policy if exists "Users can view their own recurring transactions." on recurring_transactions;
create policy "Users can view their own recurring transactions." on recurring_transactions for select using ( auth.uid() = user_id );

drop policy if exists "Users can insert their own recurring transactions." on recurring_transactions;
create policy "Users can insert their own recurring transactions." on recurring_transactions for insert with check ( auth.uid() = user_id );

drop policy if exists "Users can update their own recurring transactions." on recurring_transactions;
create policy "Users can update their own recurring transactions." on recurring_transactions for update using ( auth.uid() = user_id );

drop policy if exists "Users can delete their own recurring transactions." on recurring_transactions;
create policy "Users can delete their own recurring transactions." on recurring_transactions for delete using ( auth.uid() = user_id );
