-- Database Schema Snapshot for FinanzasApp (Dungeon Edition)
-- This file documents the expected structure of the Supabase database.

-- 1. Profiles (Standard Supabase Auth extension)
-- Linked to auth.users via triggers (handled by Supabase usually)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    updated_at TIMESTAMP WITH TIME ZONE,
    username TEXT UNIQUE,
    full_name TEXT,
    avatar_url TEXT,
    website TEXT,
    
    CONSTRAINT username_length CHECK (char_length(username) >= 3)
);

-- 2. Bank Accounts (Legacy support / Balance tracking)
CREATE TABLE IF NOT EXISTS public.bank_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    user_id UUID REFERENCES auth.users(id) NOT NULL,
    name TEXT NOT NULL,
    balance NUMERIC DEFAULT 0,
    type TEXT, -- 'checking', 'savings', 'bag_of_holding'
    currency TEXT DEFAULT 'GP'
);

-- 3. Transactions (The Ledger)
CREATE TABLE IF NOT EXISTS public.transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    user_id UUID REFERENCES auth.users(id) NOT NULL,
    amount NUMERIC NOT NULL,
    description TEXT,
    date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    type TEXT CHECK (type IN ('income', 'expense')),
    category TEXT, -- 'Food', 'Gear', 'Loot', etc.
    account_id BIGINT REFERENCES public.bank_accounts(id) -- Optional link to specific bag
);

-- 4. RLS Policies (Documentation)
-- enable row level security for all tables;
-- create policy "Users can view own data" on transactions for select using (auth.uid() = user_id);
-- create policy "Users can insert own data" on transactions for insert with check (auth.uid() = user_id);
